site_name: PembrokePStman
repo_url: https://github.com/jpsider/PembrokePStman
theme: readthedocs
pages:
- Home: index.md
- PembrokePStman Basics:
  - What is PembrokePStman: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
