site_name: PembrokePSwman
repo_url: https://github.com/jpsider/PembrokePSwman
theme: readthedocs
pages:
- Home: index.md
- PembrokePSwman Basics:
  - What is PembrokePSwman: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md
